### PR TITLE
fire AuthFailed if HMAC middleware fails auth

### LINKED ISSUE #963: mw: HMAC failure does not trigger an EventAuthFailure
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
If I call an endpoint with an invalid `Authorization` token it does not trigger a EventAuthFailure event.

**What is the expected behavior?**
I would expect an EventAuthFailure event to fire as is the case for the `JWT` or the `Auth Token` (although I might be wrong about this so please correct me before I make a PR for this).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
If I configure a WebHook for the AuthFailure event it triggers for `JWT` and `Auth Token` but not for `HMAC` if I send requests with invalid Authorization headers 

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
I am using the latest Tyk gateway from docker hub (https://hub.docker.com/r/tykio/tyk-gateway/tags/)

### PR DESCRIPTION
**Pull request by othane**
this fixes #963 so that any failure in the HMAC authorization will
fire a AuthFailed event so users can write webhooks to log possible
attacks

### CODE REVIEW

**Comment by mvdan** [comment]
You were able to write the tests - awesome :) will be reviewing this now.

File: mw_hmac_test.go [hunk 1]
```diff
@@ -69,10 +73,48 @@ func getHMACAuthChain(spec *APISpec) http.Handler {
...
 	session := createHMACAuthSession()
 
+	// Should not receive an AuthFailure event
+	var eventWG sync.WaitGroup
+	var eventAuthFailState bool = false
+	eventWG.Add(1)
+	cb := func(em config.EventMessage) {
+		eventAuthFailState = true
+		eventWG.Done()
+	}
```
Comment (mvdan) [inline mw_hmac_test.go]: You could simplify the logic here by having `waitTimeout` return whether the waitgroup finished or timed out. In the former case, it's the same as if `eventAuthFailState` was set to true.

So you can get rid of the bool, and use `if !waitTimedOut(&eventWG, 20*time.Millisecond) { ...` below.

Comment (othane) [inline mw_hmac_test.go]: good point :) ... I have updated the PR ... thanks :+1:

**Comment by mvdan** [comment]
Thanks again!

**Comment by othane** [comment]
Cool, thanks for the help, it was nice to play with Go :) 

Any idea which release this is likely be in ?

**Comment by mvdan** [comment]
2.3.8 is going out any moment now, and it includes many important fixes. We've been testing it for a bit already though, so this change isn't critical enough to warrant delaying the release.

It will for sure be included in 2.4, which should come out in the next month or two.
