### PR TITLE
TT-12965: Improve performance of ctx.GetOASDefinition/GetDefinition

### LINKED ISSUE #6471: [TT-12965] `ctx.GetOASDefinition()` has very poor performance
**Branch/Environment/Version**
- Branch/Version: 5.4.0
- Environment: On-Prem

**Describe the bug**
To work around some limitations in Tyks mTLS support (see #6259), I am maintaining a custom go plugin for mTLS at Paymenttools. We recently enhanced that plugin to support OAS APIs as well and noticed a large performance regression. 

To get custom per-api plugin configuration at runtime, the plugin calls [`ctx.GetOASDefinition`](https://github.com/TykTechnologies/tyk/blob/master/ctx/ctx.go#L143) on the context object provided to the plugin. This function performs a deep copy of the stored `*oas.OAS` object before returning it which first marshals and then unmarshals the object to JSON. 

This turns out to be a **very** expensive operation and severely degrades performance of your plugin if the function is called in the hot path for every incoming request. By removing this function and manually getting the `*oas.OAS` pointer from the passed context, we could reduce our memory usage by **95%** and CPU usage by **46%** which severely improved the overall performance of our Tyk setup.

Below you can see two generated flame graphs which show the difference (please ignore the color inconsistency). 

Memory:
mem_flamegraph

CPU:
cpu_flamegraph

**Proposed solution**

We've been running this fix for some time now in production and could not notice any negative side effects which might be explained by not operating on a deep copy of the passed OAS definition. Therefore I propose to remove the unneeded deep copy of the `*oas.OAS` object before returning it.

### PR DESCRIPTION
**Pull request by titpetric**
The *oas.OAS or *apidef.APIDefinition retrieved directly from context should be considered immutable, and depending on how plugins use the ctx package, this may cause issues. Each server request is started in a goroutine, making any map iteration dangerous due to the concurrency. By providing a deep copy that problem goes away.

The PR optimizes performance for the following functions:

- ctx.GetDefinition

This function returned the pointer to APIDefinition directly as if you would have used the context. This was a known defect until now. We now use the same deep copy mechanism that was optimized for OAS, to avoid concurrency concerns from plugins and improve stability.

- ctx.GetOASDefinition

Since we were aware of the defect of GetDefinition, this function used a naive copy mechanism to ensure that the copy is safe to use. It did rely on encoding/json, on the reasoning performance can be improved by a more optimized mechanism in the future (encoding/gob, msgpack...). Using a memory cloning approach, the following change was benchmarked, showing a reduction of latencies and allocations around -90%.

Benchmark master:

```
BenchmarkOAS_Clone     	   47610	     25781 ns/op	   15211 B/op	     206 allocs/op
BenchmarkOAS_Clone-2   	   44457	     25821 ns/op	   15214 B/op	     206 allocs/op
BenchmarkOAS_Clone-4   	   51541	     24412 ns/op	   15220 B/op	     206 allocs/op
BenchmarkOAS_Clone-8   	   47432	     27178 ns/op	   15228 B/op	     206 allocs/op
```

Benchmark PR:

```
BenchmarkOAS_Clone     	  390181	      2839 ns/op	    1408 B/op	      17 allocs/op
BenchmarkOAS_Clone-2   	  455761	      2547 ns/op	    1408 B/op	      17 allocs/op
BenchmarkOAS_Clone-4   	  436094	      2570 ns/op	    1408 B/op	      17 allocs/op
BenchmarkOAS_Clone-8   	  447078	      3100 ns/op	    1408 B/op	      17 allocs/op
```

- Improves ctx.GetOASDefinition
- Improves ctx.GetDefinition to return a copy (concurrency fix)
- Additional benchmarks added for ctx package
- Additional benchmarks added for reflect package
- Added huandu/go-clone and an internal type-generic reflect.Clone API.

Closes #6471

<details open>
  <summary><a href="https://tyktech.atlassian.net/browse/TT-12965" title="TT-12965" target="_blank">TT-12965</a></summary>
  <br />
  <table>
    <tr>
      <th>Summary</th>
      <td>[Customer PR] Improve performance of ctx.GetOASDefinition()</td>
    </tr>
    <tr>
      <th>Type</th>
      <td>
        Story
        Story
      </td>
    </tr>
    <tr>
      <th>Status</th>
      <td>In Dev</td>
    </tr>
    <tr>
      <th>Points</th>
      <td>N/A</td>
    </tr>
    <tr>
      <th>Labels</th>
      <td><a href="https://tyktech.atlassian.net/issues?jql=project%20%3D%20TT%20AND%20labels%20%3D%20customer_bug%20ORDER%20BY%20created%20DESC" title="customer_bug">customer_bug</a>, <a href="https://tyktech.atlassian.net/issues?jql=project%20%3D%20TT%20AND%20labels%20%3D%20github%20ORDER%20BY%20created%20DESC" title="github">github</a>, <a href="https://tyktech.atlassian.net/issues?jql=project%20%3D%20TT%20AND%20labels%20%3D%20jira_escalated%20ORDER%20BY%20created%20DESC" title="jira_escalated">jira_escalated</a></td>
    </tr>
  </table>
</details>

---

https://tyktech.atlassian.net/browse/TT-12965

### CODE REVIEW

**Comment by buger** [comment]
<p> A JIRA Issue ID is missing from your branch name, PR title and PR description! 🦄</p>
<p>Your branch: fix/improve-ctx-allocation-with-clone</p>
<p>Your PR title: Fix/improve ctx allocation with clone</p>
<p>Your PR description: null</p>
<p>If this is your first time contributing to this repository - welcome!</p>
<hr />
<p>Please refer to <a href="https://github.com/cleartax/jira-lint">jira-lint</a> to get started.
<p>Without the JIRA Issue ID in your branch name you would lose out on automatic updates to JIRA via SCM; some GitHub status checks might fail.</p>
Valid sample branch names:

  ‣ feature/shiny-new-feature--mojo-10'
  ‣ 'chore/changelogUpdate_mojo-123'
  ‣ 'bugfix/fix-some-strange-bug_GAL-2345'

**Comment by buger** [comment]
<p> A JIRA Issue ID is missing from your branch name, PR title and PR description! 🦄</p>
<p>Your branch: fix/improve-ctx-allocation-with-clone</p>
<p>Your PR title: Fix/improve ctx allocation with clone</p>
<p>Your PR description: null</p>
<p>If this is your first time contributing to this repository - welcome!</p>
<hr />
<p>Please refer to <a href="https://github.com/cleartax/jira-lint">jira-lint</a> to get started.
<p>Without the JIRA Issue ID in your branch name you would lose out on automatic updates to JIRA via SCM; some GitHub status checks might fail.</p>
Valid sample branch names:

  ‣ feature/shiny-new-feature--mojo-10'
  ‣ 'chore/changelogUpdate_mojo-123'
  ‣ 'bugfix/fix-some-strange-bug_GAL-2345'

File: ctx/ctx.go [hunk 1]
```diff
@@ -114,45 +115,32 @@ func SetSession(r *http.Request, s *user.SessionState, scheduleUpdate bool, hash
...
 
+// SetDefinition can be used to set a modified API definition to the request context.
 func SetDefinition(r *http.Request, s *apidef.APIDefinition) {
 	ctx := r.Context()
 	ctx = context.WithValue(ctx, Definition, s)
 	httputil.SetContext(r, ctx)
 }
 
+// GetDefinition will return a copy of the API definition valid for the request.
+// This copy is there to prevent shared API definition pointers.
```
Comment (titpetric) [inline ctx/ctx.go:126]:
```suggestion
// GetDefinition will return a deep copy of the API definition valid for the request.
```

File: ctx/ctx.go [hunk 2]
```diff
@@ -114,45 +115,32 @@ func SetSession(r *http.Request, s *user.SessionState, scheduleUpdate bool, hash
 	}
 }
 
+// SetDefinition can be used to set a modified API definition to the request context.
```
Comment (titpetric) [inline ctx/ctx.go:118]:
```suggestion
// SetDefinition sets an API definition object to the request context.
```

File: ctx/ctx.go [hunk 3]
```diff
@@ -114,45 +115,32 @@ func SetSession(r *http.Request, s *user.SessionState, scheduleUpdate bool, hash
...
-				return &def
-			}
+			return reflect.Clone(val)
 		}
 	}
+
 	return nil
 }
 
 // GetOASDefinition returns a deep copy of the OAS definition of the called API.
```
Comment (titpetric) [inline ctx/ctx.go:137]:
```suggestion
// GetOASDefinition will return a deep copy of the OAS API definition valid for the request.
```

**Comment by buger** [comment]
<p>:broken_heart: The detected issue is not in one of the allowed statuses :broken_heart: </p>    
   <table>
     <tr>
        <th>Detected Status</th>
        <td>Open</td>
        <td>:x:</td>
     </tr>
     <tr>
        <th>Allowed Statuses</th>
        <td>In Dev,In Code Review,Ready for Testing,In Test,In Progress,In Review</td>
        <td>:heavy_check_mark:</td>
      </tr>
   </table>
   <p>Please ensure your jira story is in one of the allowed statuses</p>

**Comment by buger** [comment]
<p>
    Let's make that PR title a 💯 shall we? 💪
    </p>
    <p>
    Your <em>PR title</em> and <em>story title</em> look <strong>slightly different</strong>. Just checking in to know if it was intentional!
    </p>
    <table>
      <tr>
        <th>Story Title</th>
        <td>[Customer PR] Improve performance of ctx.GetOASDefinition()</td>
      </tr>
      <tr>
          <th>PR Title</th>
          <td>TT-12965: Fix/improve ctx allocation with clone</td>
        </tr>
    </table>
    <p>
      Check out this <a href="https://www.atlassian.com/blog/git/written-unwritten-guide-pull-requests">guide</a> to learn more about PR best-practices.
    </p>

File: ctx/ctx.go [hunk 4]
```diff
@@ -114,45 +115,38 @@ func SetSession(r *http.Request, s *user.SessionState, scheduleUpdate bool, hash
...
-		return nil
-	}
-
-	val, ok := v.(*oas.OAS)
-	if !ok {
-		return nil
-	}
+// SetOASDefinition sets an OAS API definition object to the request context.
+func SetOASDefinition(r *http.Request, s *oas.OAS) {
+	ctx := r.Context()
```
Comment (jeffy-mathew) [inline ctx/ctx.go:138]: shall we use `httpctx.Value` here?

**Review by jeffy-mathew — APPROVED** [review]

**Review by andrei-tyk — APPROVED** [review]

File: ctx/ctx.go (hunk 4 above)
Comment (titpetric) [reply ctx/ctx.go:138]: Filed https://tyktech.atlassian.net/browse/TT-14063 to follow up, you can action the cleanup going forward. I'm happy with the delta here, no need to increase review surface.
