### PR TITLE
config: fatal on config parse errors, try multiple files, add tests

### LINKED ISSUE #501: Should recognize ./tyk.conf by default if configuration option not specified
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
By default, it searches configuration at `/etc/tyk/tyk.conf` location, and if it is not found, it sets default one, and writes it to `./tyk.conf`. If there is already `tyk.conf` in current directory, it will overwrite it :(

**What is the expected behavior?**
If there is local tyk.conf, it should not override it, and should actually use it.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Create local `tyk.conf` with some custom configuration. Run `tyk` without `--conf` option. `tyk.conf` will be overridden with default config.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

The proper fix will be searching tyk.conf in multiple locations.

### PR DESCRIPTION
**Pull request by mvdan**
Split in a few commits to help code review.

For now, we only read `tyk.conf` before `/etc/tyk/tyk.conf`. More paths can be easily added later, and the precedence can also be easily modified.

Fixes #501.

### CODE REVIEW

File: gateway_test.go [hunk 1]
```diff
@@ -129,6 +129,11 @@ func TestMain(m *testing.M) {
 	config.EnableJSVM = true
 	config.Monitor.EnableTriggerMonitors = true
 	config.AnalyticsConfig.NormaliseUrls.Enabled = true
+	config.SlaveOptions.CallTimeout = 30
+	config.SlaveOptions.PingTimeout = 60
+	GlobalRPCPingTimeout = time.Second * time.Duration(config.SlaveOptions.PingTimeout)
+	GlobalRPCCallTimeout = time.Second * time.Duration(config.SlaveOptions.CallTimeout)
```
Comment (buger) [inline gateway_test.go]: Why you added lines above?

**Comment by buger** [comment]
@ilijabojanovic ready for testing. 

The Proper test will be comparing default configs, generated by tyk, before and after this PR, in order to ensure that they are identical. To make this work, delete local tyk.conf file, and /etc/tyk/tyk.conf files, and run tyk without --conf option. 

And in second, create local `tyk.conf` and ensure that tyk will use it and not override if you run it without `--conf` option. Next remove local `tyk.conf` and create `/etc/tyk/tyk.conf`, and ensure that tyk will use this path, if local one not found. 

And in third, ensure that `--conf` option works with custom paths. 

👌

File: gateway_test.go (hunk 1 above)
Comment (mvdan) [inline gateway_test.go]: Because the tests would fail without them - it's explained in its commit message. To simplify the logic of what runs and what doesn't regarding the config code in `go test`, now `loadConfig` isn't ran at all. And the last thing it does is set these up.

**Comment by mvdan** [comment]
Most of the scenarios that @buger explained (except `--conf`, that's more like an integration test) are already covered by the unit tests, so hopefully it should all be OK.

File: gateway_test.go (hunk 1 above)
Comment (buger) [inline gateway_test.go]: I'll be frank, this change does not look that good, especially we if we change config options, we will have to modify them there too. 

What about moving default config into a variable outside `writeDefaultConf` function: 
```
var defaultConf = Config{
 		ListenPort:     8080,
                ....
}
```

And then use this variable in `writeDefaultConf` and test initialization: `config = defaultConf`.

Comment (mvdan) [inline gateway_test.go]: I agree that it's not ideal, but changing how the default config won't work. Note that these settings are applied *after* the config file is read, not before. Perhaps a method like `ensureConfigSanity` to do these last-step tweaks in both prod and test.

Comment (mvdan) [inline gateway_test.go]: ^ to clarify, what I mean is that I can do these changes on this PR if you want.

Comment (buger) [inline gateway_test.go]: Yeah, lets try to do it.

Comment (mvdan) [inline gateway_test.go]: done, PTAL

**Comment by mvdan** [comment]
Rebased after a few dozen commits and some minor conflicts.

**Comment by mvdan** [comment]
Okay, I give up on coveralls actually doing its job.

**Comment by ilijabojanovic** [comment]
Verified and approved for merge @buger
