### PR TITLE
coprocess_python: lock to OS thread on initialization

### LINKED ISSUE #761: GIL error when using Python bundles
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When the bundles are loaded or reloaded, a GIL error shows up. This happens intermittently.
This might be related to recent changes in the API loader.

**What is the expected behavior?**
The bundles should be loaded correctly.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Load a Python plugin, start/stop Tyk a few times.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All versions.

### LINKED ISSUE #969: GIL error when starting Tyk
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When Tyk starts it throws a Python GIL error, when loading plugins. This happens intermittently.

**What is the expected behavior?**
This is related to #761, which was for reload errors.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Add two or three API definitions that use Python plugin bundles, run Tyk.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

### PR DESCRIPTION
**Pull request by matiasinsaurralde**
Fixes #969, complementary to #758.

### CODE REVIEW

**Comment by mvdan** [comment]
The other PR, #758, called `runtime.LockOSThread()` in a very clear new goroutine. This one, however, is not a clear new goroutine, nor does it call `UnlockOSThread`.

How do you know that you're not locking the main goroutine - or another long-lived goroutine - to the OS thread? Have you looked into this?

**Comment by mvdan** [comment]
Also, doesn't this actually fix https://github.com/TykTechnologies/tyk/issues/969, the new issue?

**Comment by matiasinsaurralde** [comment]
@mvdan yes, I wrote the wrong ID, it's actually 969.

**Comment by mvdan** [comment]
We spoke privately, and we agreed that it would be best to separate the python GIL initialization work into its own, short-lived goroutine - which can then use `LockOSThread`. That way, it's easy to prove that we're not locking anything else to the OS thread.

**Comment by matiasinsaurralde** [comment]
I've been heavily testing this and came up with some enhancements like using the thread state API. This approach gives me zero crashes on Tyk initializations and reloads, finally!
To avoid refactoring all the CP logic I added some signaling inside the initialization of the Python driver (as suggested by @mvdan), so that we can return `CoProcessInit` after the cgo calls are done.
Would be great if somebody could test this up, the original issue occurs intermittently when you load more than one Python plugin bundle.

**Comment by buger** [comment]
@ilijabojanovic ^

File: coprocess_python.go [hunk 1]
```diff
@@ -295,20 +296,20 @@ func NewCoProcessDispatcher() (coprocess.Dispatcher, error) {
...
+		PythonLoadDispatcher()
+		dispatcher, err = PythonNewDispatcher(middlewarePath, eventHandlerPath, bundlePaths)
+		if err != nil {
+			log.WithFields(logrus.Fields{
+				"prefix": "coprocess",
+			}).Error(err)
+		}
+		pythonInitDone <- true
+	}()
+	<-pythonInitDone
```
Comment (mvdan) [inline coprocess_python.go]: You probably want to make `pythonInitDone` an error channel, so that the error can be returned or otherwise handled.

File: coprocess_python.go [hunk 2]
```diff
@@ -187,6 +185,9 @@ const CoProcessName = apidef.PythonDriver
 // MessageType sets the default message type.
 var MessageType = coprocess.ProtobufMessage
 
+// pythonInitDone is used to signal the end of Python initialization step
+var pythonInitDone = make(chan bool)
```
Comment (mvdan) [inline coprocess_python.go]: Is there a reason to make this a global?

If this is to reuse the channel allocation, are we sure it won't be used more than once concurrently?

File: coprocess_python.go (hunk 1 above)
Comment (mvdan) [inline coprocess_python.go]: Err, I see that you are actually returning it, but by writing to the parent's error variable instead. This is a bit unintuitive, and will break easily with data races if we ever touch this code. Better to explicitly pass the error via the channel, returning nil if there was no error.

File: coprocess_python.go [hunk 3]
```diff
@@ -86,18 +84,20 @@ static void Python_HandleMiddlewareCache(char* bundle_path) {
 }
 
 static int Python_NewDispatcher(char* middleware_path, char* event_handler_path, char* bundle_paths) {
+	PyThreadState*  mainThreadState = PyEval_SaveThread();
+	gilState = PyGILState_Ensure();
```
Comment (mvdan) [inline coprocess_python.go]: Why do we need both `runtime.LockOSThread` and this? Is this an improvement that's unrelated to the fix?

Comment (matiasinsaurralde) [inline coprocess_python.go]: We were already using `PyEval_ReleaseLock` but this is the proper/better way of using it, and this replaces the lock operations.

**Comment by matiasinsaurralde** [comment]
Updated!

**Comment by matiasinsaurralde** [comment]
@mvdan I think that to test this you need the full scenario, multiple bundles, etc. So I suggest using this in its current status and add tests on my refactoring branch (which I would update with this patch as well).

**Comment by mvdan** [comment]
Sounds good - I'm mostly concerned about regressions, given how this code is subtle and it even took us two tries to fix it fully. As long as the test makes it into 2.4, we're good :)

**Comment by ilijabojanovic** [comment]
@buger approved for merge
