### PR TITLE
Change redis client logic and deprecate hosts with addrs in redis conf

### LINKED ISSUE #2742: Gateway: go-redis driver issues with redis cluster
**Branch/Environment/Version**
- Branch/Version: release-2.9/master
- Environment: All

**Describe the bug**
Gateway can't connect on redis cluster with go-redis driver

**Reproduction steps**

1. Enable redis cluster in tyk.conf
2. Start gateway

**Actual behavior**
```
[Dec 16 23:44:40]  INFO Redis connection pools are ready after number of retires currRetry=0
[Dec 16 23:44:40]  INFO main: Redis connection pools are ready
[Dec 16 23:44:40]  INFO main: Initialising Tyk REST API Endpoints
[Dec 16 23:44:40]  INFO main: --> Using TLS (https)
[Dec 16 23:44:40]  WARN main: Starting HTTP server on:[::]:8181
[Dec 16 23:44:40]  INFO dashboard: Registering gateway node with Dashboard
[Dec 16 23:44:40] ERROR dashboard: Request failed with error Get http://www.tyk-test.com:3000/register/node: dial tcp 127.0.0.1:3000: connect: connection refused; retrying in 5s
[Dec 16 23:44:41] ERROR Error trying to get TTL: MOVED 609 127.0.0.1:7000
[Dec 16 23:44:41] ERROR Could not EXPIRE key: MOVED 609 127.0.0.1:7000
[Dec 16 23:44:42] ERROR Error trying to get TTL: MOVED 609 127.0.0.1:7000
[Dec 16 23:44:42] ERROR Could not EXPIRE key: MOVED 609 127.0.0.1:7000
[Dec 16 23:44:43] ERROR Error trying to get TTL: MOVED 609 127.0.0.1:7000
[Dec 16 23:44:43] ERROR Could not EXPIRE key: MOVED 609 127.0.0.1:7000
[Dec 16 23:44:44] ERROR Error trying to get TTL: MOVED 609 127.0.0.1:7000
[Dec 16 23:44:44] ERROR Could not EXPIRE key: MOVED 609 127.0.0.1:7000
[Dec 16 23:44:45] ERROR Error trying to get TTL: MOVED 609 127.0.0.1:7000
[Dec 16 23:44:45] ERROR Could not EXPIRE key: MOVED 609 127.0.0.1:7000
[Dec 16 23:44:45]  INFO dashboard: Registering gateway node with Dashboard
[Dec 16 23:44:45] ERROR dashboard: Request failed with error Get http://www.tyk-test.com:3000/register/node: dial tcp 127.0.0.1:3000: connect: connection refused; retrying in 5s
```

**Expected behavior**
Gateway should connect to redis sluter

**Screenshots/Video**
If applicable, add screenshots or video to help explain your problem.

**Logs (debug mode or log file):**
Log from console or from log file.

**Configuration (tyk config file):**
Attach tyk configuration file

**Additional context**
Tested on redis 5.0.5, 5.0.3, 5.0.1 version with 3 redis master's and 3 replicas

### PR DESCRIPTION
**Pull request by furkansenharputlu**
This PR deprecates `hosts` field in redis configuration. Instead `addrs` is defined. Example:
```
"addrs": [
"localhost:30001",
"localhost:30002",
"localhost:30003"
],
```

Also, this PR changes the redis client definition logic. The old version was defining cluster client if given address number is more than one. Otherwise, it was defining a simple redis client.
With this PR, if `enable_cluster` is `true`, the client will be automatically defined as cluster client no matter number of given addresses in config.

Fixes #2742

### CODE REVIEW

File: storage/redis_cluster.go [hunk 1]
```diff
@@ -159,11 +156,90 @@ func NewRedisClusterPool(isCache bool) redis.UniversalClient {
...
 		TLSConfig:    tlsConfig,
-	})
+	}
+
+	if cfg.EnableCluster {
+		log.Info("--> [REDIS] Using clustered mode")
+		client = redis.NewClusterClient(opts.cluster())
+	} else {
+		log.Info("--> [REDIS] Using single node mode")
+		client = redis.NewClient(opts.simple())
```
Comment (buger) [inline storage/redis_cluster.go]: As mentioned previously, lets then add smth like:
``
	else if opts.MasterName != "" {
		return NewFailoverClient(opts.failover())
       }
```

Comment (buger) [reply storage/redis_cluster.go]: As discussed in Slack will be separate PR

**Comment by buger** [comment]
Linter test is failing ^
