### PR TITLE
#1179 If use_db_app_configs is set to false, reLogin will no longer panic

### LINKED ISSUE #1179: Panic with policy request auth failure
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
When calling hot reload via API

```
tyk-gateway_1    | time="Sep 30 12:12:22" level=info msg="Reload URL Structure - Scheduled" 
tyk-gateway_1    | time="Sep 30 12:12:22" level=info msg="Reload queued" 
tyk-gateway_1    | time="Sep 30 12:12:22" level=info msg="Initiating reload" 
tyk-gateway_1    | time="Sep 30 12:12:22" level=info msg="Loading policies" 
tyk-gateway_1    | time="Sep 30 12:12:22" level=info msg="Using Policies from Dashboard Service" 
tyk-gateway_1    | time="Sep 30 12:12:22" level=info msg="Mutex lock acquired... calling" 
tyk-gateway_1    | time="Sep 30 12:12:22" level=info msg="Calling dashboard service for policy list" 
tyk-gateway_1    | time="Sep 30 12:12:22" level=error msg="Policy request login failure, Response was: {\"Status\":\"Error\",\"Message\":\"Authorization failed (Nonce empty)\",\"Meta\":null}\n" 
tyk-gateway_1    | time="Sep 30 12:12:22" level=info msg="Registering node (again)." 
tyk-gateway_1    | panic: runtime error: invalid memory address or nil pointer dereference
tyk-gateway_1    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xb1215f]
tyk-gateway_1    | 
tyk-gateway_1    | goroutine 109 [running]:
tyk-gateway_1    | main.reLogin()
tyk-gateway_1    |      /develop/go/src/github.com/TykTechnologies/tyk/dashboard_register.go:43 +0x1df
tyk-gateway_1    | main.LoadPoliciesFromDashboard(0xc42030db00, 0x29, 0xc4201f8000, 0x20, 0xc42030db01, 0x0)
tyk-gateway_1    |      /develop/go/src/github.com/TykTechnologies/tyk/policy.go:130 +0x150a
tyk-gateway_1    | main.getPolicies()
tyk-gateway_1    |      /develop/go/src/github.com/TykTechnologies/tyk/main.go:248 +0xb58
tyk-gateway_1    | main.doReload()
tyk-gateway_1    |      /develop/go/src/github.com/TykTechnologies/tyk/main.go:551 +0x37
tyk-gateway_1    | main.reloadLoop(0xc4205147e0)
tyk-gateway_1    |      /develop/go/src/github.com/TykTechnologies/tyk/main.go:604 +0x102
tyk-gateway_1    | created by main.start
tyk-gateway_1    |      /develop/go/src/github.com/TykTechnologies/tyk/main.go:1081 +0x180
compose_tyk-gateway_1 exited with code 2
```

**What is the expected behavior?**
Should not panic

### PR DESCRIPTION
**Pull request by MangoMM**
Resolves #1179. 

When a 403 response is received from the dashboard, will no longer try to reLogin.

### CODE REVIEW

File: dashboard_register.go [hunk 1]
```diff
@@ -37,6 +37,14 @@ type HTTPDashboardHandler struct {
 }
 
 func reLogin() {
+	if !config.Global.UseDBAppConfigs {
+		log.WithFields(logrus.Fields{
+			"prefix": "main",
+		}).Info("Skipping reLogin as UseDBAppConfigs is set to false.")
```
Comment (mvdan) [inline dashboard_register.go]: I would honestly not log this, as this should be transparent to the user (and the message itself is internal).

File: policy_test.go [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+
+	oldUseDBAppConfigs := config.Global.UseDBAppConfigs
+	config.Global.UseDBAppConfigs = false
+
+	defer func() {
+		config.Global.UseDBAppConfigs = oldUseDBAppConfigs
+	}()
+
+	connStr := ts.URL
+	secret := "supersecret"
```
Comment (mvdan) [inline policy_test.go]: I would just use an empty string directly in the call, given how it's not important.

File: policy_test.go [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+	defer ts.Close()
+
+	oldUseDBAppConfigs := config.Global.UseDBAppConfigs
+	config.Global.UseDBAppConfigs = false
+
+	defer func() {
+		config.Global.UseDBAppConfigs = oldUseDBAppConfigs
+	}()
+
+	connStr := ts.URL
```
Comment (mvdan) [inline policy_test.go]: no need for a var if it's used exactly once and doesn't help readability

File: policy_test.go [hunk 4]
```diff
@@ -0,0 +1,34 @@
...
+		w.WriteHeader(403)
+	}))
+	defer ts.Close()
+
+	oldUseDBAppConfigs := config.Global.UseDBAppConfigs
+	config.Global.UseDBAppConfigs = false
+
+	defer func() {
+		config.Global.UseDBAppConfigs = oldUseDBAppConfigs
+	}()
```
Comment (mvdan) [inline policy_test.go]: nit: you can do this in a single line, like:

    defer func() { foo = bar }()
