### PR TITLE
Fix "skip_url_cleaning" by not using DefaultServeMux

### LINKED ISSUE #1093: Skip URL cleaning isn't working
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When the custom HTTP server options are used and the "skip_url_cleaning" flag is enabled, the URL cleaning is still triggered.

**What is the expected behavior?**
The URL cleaning process should not occur. Seems like a regression of #377.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Enable "skip_url_cleaning".
Create an API
Send a request like "http://localhost:8080/test-api/http://tyk.io": a redirect to  "http://localhost:8080/test-api/http:/tyk.io" happens (this shouldn't happen)

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Latest version.

### PR DESCRIPTION
**Pull request by buger**
The issue itself happen because we wrap `gorilla.Mux` router through `http.ServeMux`, which is kinda wrong, because `Mux` is already a `ServeMux` implementation. So we processing routes twice.

Default `ServeMux` implementation have own route sanitization logic, and can’t be configured with `SkipClean` option, like gorilla implementation.

The solution here is to stop using ServeMux and use Gorilla directly.

Problem with this approach is that we need to reload, eg. replace, the router inside `doReload` function. Neither gorilla or ServeMux support replacing the routes, so replacing the whole router object is the only solution. When we pass raw Gorilla Router object to the `Server.Handler`, and replace `mainRouter` in `doReload`, server do not see the changes: thats why we had issues when API reloads was not working.

There are 2 ways to solve this issue: expose server object as a global variable, and dynamically replace `Handler` attribute, or write simple `http.Handler` wrapper around `mainRouter`, which always calls the current router.

I’m not sure about safety of this approach but since previously we replaced `DefaultServeMux` directly, and had no any issues, I may assume that it should be thread safe.

Should fix #1093

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -563,18 +563,15 @@ func doReload() {
 	log.WithFields(logrus.Fields{
 		"prefix": "main",
 	}).Info("Preparing new router")
-	newRouter := mux.NewRouter()
-	mainRouter = newRouter
+	mainRouter = mux.NewRouter()
+	if globalConf.HttpServerOptions.OverrideDefaults {
```
Comment (buger) [inline main.go]: This is also a new addition, which I proposed in https://github.com/TykTechnologies/tyk/pull/1094.
Since we creating a new router, we should re-apply same router settings.

File: main.go [hunk 2]
```diff
@@ -1190,6 +1187,13 @@ func startDRL() {
 	startRateLimitNotifications()
 }
 
+// The only purpose is to allow mainRouter to be dynamically replaced
+type appHandler struct{}
```
Comment (mvdan) [inline main.go]: I'd call this `mainHandler` to clarify that it's always linked to `mainRouter`.

Also, please use the godoc format as in `mainHandler's only purpose is...`

File: gateway_test.go [hunk 3]
```diff
@@ -1029,3 +1030,48 @@ func TestProxyUserAgent(t *testing.T) {
...
+		specBytes, _ := json.Marshal(spec)
+		specFilePath := filepath.Join(globalConf.AppPath, spec.APIID+strconv.Itoa(i)+".json")
+		ioutil.WriteFile(specFilePath, specBytes, 0644)
+		defer os.Remove(specFilePath)
+	}
+
+	doReload()
+}
+
+func TestSkipUrlCleanning(t *testing.T) {
```
Comment (mvdan) [inline gateway_test.go]: `Cleaning`

File: gateway_test.go [hunk 4]
```diff
@@ -1029,3 +1030,48 @@ func TestProxyUserAgent(t *testing.T) {
 		}
 	}
 }
+
+func buildAndLoadAPI(apiGens ...func(spec *APISpec)) {
```
Comment (mvdan) [inline gateway_test.go]: I'd make this use a temporary AppPath directory instead - we already do this in other tests. It's the best way to ensure that nothing else is in the dir, and that even if we panic, we won't leave anything behind. And you can delete with a single `os.RemoveAll` call.

File: gateway_test.go [hunk 5]
```diff
@@ -1029,3 +1030,48 @@ func TestProxyUserAgent(t *testing.T) {
...
+	for i, gen := range apiGens {
+		spec := &APISpec{APIDefinition: &apidef.APIDefinition{}}
+		json.Unmarshal([]byte(sampleAPI), spec)
+		gen(spec)
+		specBytes, _ := json.Marshal(spec)
+		specFilePath := filepath.Join(globalConf.AppPath, spec.APIID+strconv.Itoa(i)+".json")
+		ioutil.WriteFile(specFilePath, specBytes, 0644)
```
Comment (mvdan) [inline gateway_test.go]: Check for an error here, just in case.

File: gateway_test.go [hunk 6]
```diff
@@ -1029,3 +1030,48 @@ func TestProxyUserAgent(t *testing.T) {
 		}
 	}
 }
+
+func buildAndLoadAPI(apiGens ...func(spec *APISpec)) {
+	for i, gen := range apiGens {
+		spec := &APISpec{APIDefinition: &apidef.APIDefinition{}}
+		json.Unmarshal([]byte(sampleAPI), spec)
```
Comment (mvdan) [inline gateway_test.go]: Unmarshal into `spec.APIDefinition`, just in case

File: main.go (hunk 1 above)
Comment (mvdan) [reply main.go]: I wonder how this ever worked properly before this change.

File: gateway_test.go (hunk 6 above)
Comment (buger) [reply gateway_test.go]: Not sure what you mean here

Comment (mvdan) [reply gateway_test.go]: `sampleAPI` is an `APIDefinition`, not an `APISpec`. One is embedded into the other, so in practice it's probably fine, but it could cause issues if any field names ever conflict or if the JSON string ever includes fields directly from `APISpec`.

So I'm saying that you should do `json.Unmarshal([]byte(sampleAPI), spec.APIDefinition)`, to make sure none of those are possible.

Comment (buger) [reply gateway_test.go]: 👌

File: main.go (hunk 1 above)
Comment (buger) [reply main.go]: It did not worked :)

**Comment by buger** [comment]
Fixed comments

**Comment by ilijabojanovic** [comment]
@buger approved for merge
