### PR TITLE
cache: EnabledForSpec should just use EnableCache

### LINKED ISSUE #1329: Caching: Cache all safe request does not work
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
Cache all safe requests" does not work for protected api's
**What is the expected behavior?**
When we enable "Cache all safe requests", we should cache requests and see them in redis
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. Create protected api definition 
2. Generate key for protected api definition
3. Trigger get/post requests to gateway 
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Release 2.4

### PR DESCRIPTION
**Pull request by mvdan**
Don't require there to be a cached extended path too. Otherwise, one
can't use any sort of caching on an API without adding cached extended
paths.

At the same time, don't run the middleware if there are any cached
extended paths yet EnableCache is false. The docs tell the user to
enable the cache for the whole API, so that is expected.

Add a test to prove that caching of a simple API works. This test was
failing before, as the API does not have any cached extended paths.

Fixes #1329.

### CODE REVIEW

File: mw_redis_cache.go [hunk 1]
```diff
@@ -37,15 +37,7 @@ func (m *RedisCacheMiddleware) Init() {
 }
 
 func (m *RedisCacheMiddleware) EnabledForSpec() bool {
-	if !m.Spec.CacheOptions.EnableCache {
-		return false
-	}
-	for _, version := range m.Spec.VersionData.Versions {
```
Comment (buger) [inline mw_redis_cache.go]: I think it was sort of optimization here, to not run this middleware all the time. 
And it could be fixed without removing this `for` loop and adding an additional check like:
```
if m.Spec.CacheOptions.CacheAllSafeRequests {
   return true
}
```

Comment (mvdan) [reply mw_redis_cache.go]: Sure - but with this PR, the middleware does *not* run all the time. It only runs if caching is enabled.

And when it's enabled but only for some cases, the cases that end up not having the caching run the middleware for very little time. They are discarded very early on in ProcessRequest.

I think it is best if we just keep it simple, as we have clearly fucked it up once already. And the even more complex logic would still have edge cases. For example, what if caching is enabled, but `CacheAllSafeRequests` is false and there are no cached extended paths? I'm not that sure that the middleware should be removed entirely in such a case.

Or, to put it another way, what would `EnableCache` even be for, if we didn't rely on it here?

Comment (buger) [reply mw_redis_cache.go]: Yeah, I'm ok with the current solution too, it should work well. Just needs to be confirmed.

Comment (mvdan) [reply mw_redis_cache.go]: To clarify - I also started tweaking the current heuristic, instead of just reducing it to the one bool field. But after thinking about it a little bit, I realised it was silly and overly complex.
