### PR TITLE
Fix body transform with cache plugin

### LINKED ISSUE #2137: response body transform with cache plugin fails
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Body transform with cache plugin fails

```
curl http://tyk.gateway.lb/httpbin/xml -i
HTTP/1.1 200 OK
Server: nginx/1.14.1
Date: Mon, 25 Feb 2019 13:33:19 GMT
Content-Type: application/json
Content-Length: 219
Connection: keep-alive
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
X-Ratelimit-Limit: 0
X-Ratelimit-Remaining: 0
X-Ratelimit-Reset: 0
X-Tyk-Cached-Response: 1

<?xml version='1.0' encoding='us-ascii'?>

<!--  A SAMPLE set of slides  -->

<slideshow
    title="Sample Slide Show"
    date="Date of publication"
    author="Yours Truly"
    >

    <!-- TITLE SLIDE -->
    <slide
```

**What is the expected behavior?**

```json
curl http://tyk.gateway.lb/httpbin/xml -i
HTTP/1.1 200 OK
Server: nginx/1.14.1
Date: Mon, 25 Feb 2019 13:34:17 GMT
Content-Type: application/json
Content-Length: 219
Connection: keep-alive
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
X-Ratelimit-Limit: 0
X-Ratelimit-Remaining: 0
X-Ratelimit-Reset: 0
X-Tyk-Cached-Response: 1

{"slideshow":{"-author":"Yours Truly","-date":"Date of publication","-title":"Sample Slide Show","slide":[{"-type":"all","title":"Wake up to WonderWidgets!"},{"-type":"all","item":["Why","","Who"],"title":"Overview"}]}}
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

```json
{
  "api_model": {},
  "api_definition": {
    "api_id": "46a263f898844f4a583681da99606509",
    "jwt_issued_at_validation_skew": 0,
    "upstream_certificates": {},
    "use_keyless": true,
    "enable_coprocess_auth": false,
    "custom_middleware": {
      "pre": [],
      "post": [],
      "post_key_auth": [],
      "auth_check": {
        "name": "",
        "path": "",
        "require_session": false
      },
      "response": [],
      "driver": "",
      "id_extractor": {
        "extract_from": "",
        "extract_with": "",
        "extractor_config": {}
      }
    },
    "disable_quota": false,
    "custom_middleware_bundle": "",
    "cache_options": {
      "cache_timeout": 60,
      "enable_cache": true,
      "cache_all_safe_requests": false,
      "cache_response_codes": [],
      "enable_upstream_cache_control": false,
      "cache_control_ttl_header": ""
    },
    "enable_ip_blacklisting": false,
    "tag_headers": [],
    "pinned_public_keys": {},
    "expire_analytics_after": 0,
    "domain": "",
    "openid_options": {
      "providers": [],
      "segregate_by_client": false
    },
    "active": true,
    "jwt_expires_at_validation_skew": 0,
    "config_data": {},
    "notifications": {
      "shared_secret": "",
      "oauth_on_keychange_url": ""
    },
    "auth": {
      "auth_header_name": "",
      "use_certificate": false
    },
    "check_host_against_uptime_tests": false,
    "auth_provider": {
      "name": "",
      "storage_engine": "",
      "meta": {}
    },
    "blacklisted_ips": [],
    "hmac_allowed_clock_skew": -1,
    "dont_set_quota_on_create": false,
    "uptime_tests": {
      "check_list": [],
      "config": {
        "expire_utime_after": 0,
        "service_discovery": {
          "use_discovery_service": false,
          "query_endpoint": "",
          "use_nested_query": false,
          "parent_data_path": "",
          "data_path": "",
          "cache_timeout": 60
        },
        "recheck_wait": 0
      }
    },
    "enable_jwt": false,
    "do_not_track": false,
    "name": "httpbin",
    "slug": "httpbin",
    "oauth_meta": {
      "allowed_access_types": [],
      "allowed_authorize_types": [],
      "auth_login_redirect": ""
    },
    "CORS": {
      "enable": false,
      "max_age": 24,
      "allow_credentials": false,
      "exposed_headers": [],
      "allowed_headers": [],
      "options_passthrough": false,
      "debug": false,
      "allowed_origins": [],
      "allowed_methods": []
    },
    "event_handlers": {
      "events": {}
    },
    "proxy": {
      "target_url": "http://httpbin.org/",
      "endpoint_returns_list": false,
      "cache_timeout": 0,
      "parent_data_path": "",
      "service_discovery": {
        "endpoint_returns_list": false,
        "cache_timeout": 0,
        "parent_data_path": "",
        "query_endpoint": "",
        "use_discovery_service": false,
        "target_path": "",
        "use_target_list": false,
        "use_nested_query": false,
        "data_path": "",
        "port_data_path": ""
      },
      "check_host_against_uptime_tests": false,
      "transport": {
        "ssl_ciphers": [],
        "ssl_min_version": 0,
        "proxy_url": ""
      },
      "target_list": [],
      "query_endpoint": "",
      "use_discovery_service": false,
      "_sd_show_port_path": false,
      "preserve_host_header": false,
      "use_target_list": false,
      "strip_listen_path": true,
      "use_nested_query": false,
      "data_path": "",
      "port_data_path": "",
      "enable_load_balancing": false,
      "listen_path": "/httpbin/",
      "disable_strip_slash": false
    },
    "client_certificates": [],
    "use_basic_auth": false,
    "version_data": {
      "not_versioned": true,
      "default_version": "",
      "versions": {
        "Default": {
          "name": "Default",
          "expires": "",
          "paths": {
            "ignored": [],
            "white_list": [],
            "black_list": []
          },
          "use_extended_paths": true,
          "global_headers": {},
          "global_headers_remove": [],
          "global_size_limit": 0,
          "override_target": "",
          "extended_paths": {
            "cache": [
              "xml"
            ],
            "transform": [],
            "transform_response": [
              {
                "template_data": {
                  "input_type": "xml",
                  "template_mode": "blob",
                  "template_source": "e3sgLiB8IGpzb25NYXJzaGFsIH19",
                  "input": "",
                  "output": ""
                },
                "path": "xml",
                "method": "GET",
                "fromDashboard": true
              }
            ],
            "transform_headers": [],
            "transform_response_headers": [
              {
                "delete_headers": [],
                "add_headers": {
                  "Content-Type": "application/json"
                },
                "path": "xml",
                "method": "GET",
                "act_on": false,
                "fromDashboard": true
              }
            ]
          }
        }
      }
    },
    "use_standard_auth": false,
    "session_lifetime": 0,
    "hmac_allowed_algorithms": [],
    "disable_rate_limit": false,
    "definition": {
      "location": "header",
      "key": "x-api-version",
      "strip_path": false
    },
    "use_oauth2": false,
    "jwt_not_before_validation_skew": 0,
    "allowed_ips": [],
    "org_id": "5bffbf8ef461e30001136627",
    "enable_ip_whitelisting": false,
    "global_rate_limit": {
      "rate": 0,
      "per": 0
    },
    "enable_context_vars": false,
    "tags": [],
    "basic_auth": {
      "disable_caching": false,
      "cache_ttl": 0
    },
    "session_provider": {
      "name": "",
      "storage_engine": "",
      "meta": {}
    },
    "strip_auth_data": false,
    "id": "5c73ee0f08cbf30001cc6629",
    "certificates": [],
    "enable_signature_checking": false,
    "use_openid": false,
    "jwt_skip_kid": false,
    "enable_batch_request_support": false,
    "response_processors": [
      {
        "name": "header_injector",
        "options": {}
      },
      {
        "name": "response_body_transform",
        "options": {}
      }
    ],
    "use_mutual_tls_auth": false
  },
  "hook_references": [],
  "is_site": false,
  "sort_by": 0
}
```

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**

### PR DESCRIPTION
**Pull request by furkansenharputlu**
`WrappedServeHTTP` is copying a response without handling body transformations. Then, it returns the early copied value. So, the actual response is cached. This PR prioritizes the body transformation.

Fixes #2137.

### CODE REVIEW

File: res_handler_transform_test.go [hunk 1]
```diff
@@ -127,3 +127,52 @@ func TestTransformResponse_ContextVars(t *testing.T) {
...
+		{Path: path, Headers: map[string]string{"Foo": "Bar2"}, Code: 200, BodyMatch: `{"foo":"Bar2"}`},
+	}...)
+
+	// with cache
+	createAPI(true)
+
+	ts.Run(t, []test.TestCase{
+		{Path: path, Headers: map[string]string{"Foo": "Bar"}, Code: 200, BodyMatch: `{"foo":"Bar"}`},  // Returns response and caches it
+		{Path: path, Headers: map[string]string{"Foo": "Bar2"}, Code: 200, BodyMatch: `{"foo":"Bar"}`}, // Returns cached response directly
+	}...)
```
Comment (komalsukhani) [inline res_handler_transform_test.go]: In last testcase, BodyMatch should contain {"foo":"Bar2"}, right?

Comment (furkansenharputlu) [reply res_handler_transform_test.go]: yes

Comment (furkansenharputlu) [reply res_handler_transform_test.go]: Nope, it makes sure that the cache is working.
