### PR TITLE
Fix Uptime tests reverse logic

### LINKED ISSUE #632: Upstream targets not taken out of pool when upstream tests fail
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Uptime Tests feature doesn't work well, with this option enabled gateway sends traffic on host which is down
**What is the expected behavior?**
Gateway should exclude down host from routing 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Current Master and Stable 2.3.3

More details:
https://community.tyk.io/t/upstream-targets-not-taken-out-of-pool-when-upstream-tests-fail/1481

### PR DESCRIPTION
**Pull request by buger**
Should fix #632

When limit set to 1, it did not mark host as failed and continue sending traffic to it, until next host check. Worth noticing that now it also use `>=` logic instead of `>`, so it will trigger failed host check earlier than before, but it looks more logical: if `trigger_limit` set to 1, we want to send notification on the first failure. 

Also, fixed Uptime tests reverse logic: `IsHostDown` function currently has reverse logic, and returns true for active hosts. Fun thing, Tyk still works fine because `GetNextTarget` have reverse
logic as well, and they fix each other :)

Writing tests for this functionality was tricky because functionality spread up across the app, but thankfully we can set the callback, similar to how webhooks work, and it worked quite well. 

Added test covering part of uptime tests functionality.

### CODE REVIEW

**Comment by buger** [comment]
tip: better to review with white space check turned off https://github.com/TykTechnologies/tyk/pull/635/files?w=1

File: host_checker.go [hunk 1]
```diff
@@ -104,23 +104,23 @@ func (h *HostUptimeChecker) HostReporter() {
...
-					log.Debug("[HOST CHECKER] [HOST WARNING]: ", failedHost.CheckURL)
-					// Reset the count
-					go h.sampleCache.Set(failedHost.ID, 1, cache.DefaultExpiration)
-					// track it
-					h.unHealthyList[failedHost.ID] = true
-					// Call the custom callback hook
-					go h.failureCallback(failedHost)
-				}
+			newVal := cachedHostCount.(int)
+			newVal++
```
Comment (mvdan) [inline host_checker.go]: You could instead do:

```
newVal := 1
if count, found := h.sampleCache.Get(failedHost.ID); found {
    newVal = count.(int) + 1
}

File: host_checker.go [hunk 2]
```diff
@@ -104,23 +104,23 @@ func (h *HostUptimeChecker) HostReporter() {
...
+			go h.sampleCache.Set(failedHost.ID, newVal, cache.DefaultExpiration)
+
+			if newVal >= h.sampleTriggerLimit {
+				log.Debug("[HOST CHECKER] [HOST WARNING]: ", failedHost.CheckURL)
+				// Reset the count
+				go h.sampleCache.Set(failedHost.ID, 1, cache.DefaultExpiration)
```
Comment (mvdan) [inline host_checker.go]: What if the `Set` above happens to run after the one here? Do we really need to fire the two goroutines, ever?

(I know this is not your code and it's not modified in this PR, but still)

File: host_checker_manager.go [hunk 3]
```diff
@@ -282,7 +282,7 @@ func (hc *HostCheckerManager) IsHostDown(urlStr string) bool {
 	_, err = hc.store.GetKey(PoolerHostSentinelKeyPrefix + u.Host)
 
 	// Found a key, the host is down
```
Comment (mvdan) [inline host_checker_manager.go]: Ha! The comment was right, the code was wrong :)

File: host_checker_test.go [hunk 4]
```diff
@@ -0,0 +1,123 @@
...
+
+	wg.Wait()
+
+	if GlobalHostChecker.IsHostDown("http://127.0.0.1:16500") {
+		t.Error("Should not mark as down")
+	}
+
+	if !GlobalHostChecker.IsHostDown("http://127.0.0.1:16501") {
+		t.Error("Should mark as down")
+	}
```
Comment (mvdan) [inline host_checker_test.go]: Perhaps I'm blind, but what is making `:16500` up and `:16501` down?

Comment (mvdan) [inline host_checker_test.go]: Oh duh, this is the port I used for the test http server that replaced httpbin.

I suggest you use these constants:

```
testHttpListen = "127.0.0.1:16500"
testHttpAny  = "http://" + testHttpListen
```

Otherwise it's not obvious from reading just this code, and it's also fragile since it will break if the port ever changes.

Comment (buger) [inline host_checker_test.go]: Yeah, I made it hardcoded to avoid variable replace or templates.

Comment (mvdan) [inline host_checker_test.go]: Sorry, I don't understand. In my opinion reusing the constants is better in every way.

**Comment by buger** [comment]
@mvdan made the changes

File: host_checker_test.go [hunk 5]
```diff
@@ -0,0 +1,138 @@
...
+        "listen_path": "/",
+        "enable_load_balancing": true,
+        "check_host_against_uptime_tests": true,
+        "target_list": [
+            "{{.ActiveHost}}",
+            "{{.InactiveHost}}"
+        ],
+        "strip_listen_path": true
+    },
+    "active": true
```
Comment (mvdan) [inline host_checker_test.go]: please indent with tabs for consistency

File: host_checker_test.go (hunk 4 above)
Comment (mvdan) [inline host_checker_test.go]: Bump

**Comment by buger** [comment]
Should be good now

**Comment by JasonSheedy** [comment]
Awesome guys. Thanks for fixing this.
