### PR TITLE
Override oauth errors with global config

### LINKED ISSUE #2897: Allow configure whitelist/blacklist ignore option on global and API level.
**Branch/Environment/Version**
- Branch/Version: 2.9

**Describe the bug**
When we introduced "ignore" option for whitelist/blacklist plugin, we actually broke compatibility with previous versions. These plugins now started respecting the case by default (while previously it was not the case). https://github.com/TykTechnologies/tyk/pull/2339/files

We need a way to make it behave like previously, by adding `ignore` param on the API and Global levels (tyk.conf)

### PR DESCRIPTION
**Pull request by furkansenharputlu**
This PR defines a new config variable: `override_messages` to override error messages and codes. Example usage:
```
"override_messages": {
        "oauth.auth_field_missing" : {
            "code": 401,
            "message": "Token is not authorised"
        }
    }
```
The following are the configurable errors for now:
```
"auth.auth_field_missing"
"auth.key_not_found"

"oauth.auth_field_missing"
"oauth.auth_field_malformed"
"oauth.key_not_found"
"oauth.client_deleted"
```

Also, it is possible to override only error code or only error message. Like this:
 ```
"override_messages": {
        "oauth.auth_field_missing" : {
            "code": 401,
        }
    }
```
Fixes https://github.com/TykTechnologies/tyk/issues/2900

### CODE REVIEW

File: config/config.go [hunk 1]
```diff
@@ -464,6 +464,16 @@ type Config struct {
 
 	// Secrets are key-value pairs that can be accessed in the dashboard via "secrets://"
 	Secrets map[string]string `json:"secrets"`
+
+	// TykErrors is used to override returned API error codes and messages.
+	TykErrors map[TykErrorType]TykError `bson:"tyk_errors" json:"tyk_errors"`
+}
+
+type TykErrorType string
```
Comment (buger) [inline config/config.go]: Maybe rename it to`TykErrorID`?

File: config/config.go [hunk 2]
```diff
@@ -464,6 +464,16 @@ type Config struct {
 
 	// Secrets are key-value pairs that can be accessed in the dashboard via "secrets://"
 	Secrets map[string]string `json:"secrets"`
+
+	// TykErrors is used to override returned API error codes and messages.
+	TykErrors map[TykErrorType]TykError `bson:"tyk_errors" json:"tyk_errors"`
```
Comment (buger) [inline config/config.go]: Maybe align it with what we already have in python plugins, and name it `override_errors`? 
Note that in future we can add a notation to override upstream server errors too.

File: gateway/handler_error.go [hunk 3]
```diff
@@ -20,6 +23,54 @@ const (
 	defaultContentType    = headers.ApplicationJSON
 )
 
+const (
+	OAuthAuthorizationFieldMissing config.TykErrorType = "oauth.auth_field_missing"
+	OAuthBearerTokenMalformed      config.TykErrorType = "oauth.bearer_token_malformed"
+	OAuthKeyNotAuthorised          config.TykErrorType = "oauth.key_not_authorised"
+	OAuthClientDeleted             config.TykErrorType = "oauth.client_deleted"
```
Comment (buger) [inline gateway/handler_error.go]: Suggest to add Err postfix or prefix, to have consistent notation: `OAuthAuthorizationFieldMissingErr` or `ErrOAuthAuthorizationFieldMissing`

File: gateway/handler_error.go [hunk 4]
```diff
@@ -20,6 +23,54 @@ const (
...
+)
+
+var TykErrors = map[config.TykErrorType]config.TykError{
```
Comment (buger) [inline gateway/handler_error.go]: We probably should initialize map somewhere else. And each file can define its errors inside `init` function or similar.

File: config/config.go (hunk 1 above)
Comment (buger) [reply config/config.go]: On the other hand, maybe we do not need a separate type for it at all

**Comment by buger** [comment]
Let's normalize messages like this:

"auth.auth_field_missing" -> stays as it is
"auth.nonexistent_key" -> "auth.key_not_found"

"oauth.auth_field_missing" -> stays as it is
"oauth.bearer_token_malformed" -> "oauth.auth_field_malformed"
"oauth.key_not_authorised" -> "oauth.key_not_found"
"oauth.client_deleted" -> stays as it is
