### PR TITLE
session: make MetaData a map[string]string

### LINKED ISSUE #944: Meta data header value of integer type produces a panic
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
```
[Jul 25 16:22:54] ERROR Regex error: error parsing regexp: missing argument to repetition operator: `*`
2017/07/25 16:22:54 http: panic serving 1.2.3.4:50818: interface conversion: interface is float64, not string
goroutine 9736 [running]:
net/http.(*conn).serve.func1(0xc421423d80)
        /usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0xccdc60, 0xc4213cecc0)
        /usr/local/go/src/runtime/panic.go:458 +0x243
main.(*TransformHeaders).iterateAddHeaders(0xc42191e908, 0xc421218030, 0xc42153b590)
        /src/github.com/TykTechnologies/tyk/middleware_modify_headers.go:81 +0x3ea
main.(*TransformHeaders).ProcessRequest(0xc42191e908, 0x12b3220, 0xc4202c7c70, 0xc42153b590, 0x0, 0x0, 0x19, 0x2, 0x4)
        /src/github.com/TykTechnologies/tyk/middleware_modify_headers.go:157 +0x49b
main.CreateMiddleware.func1.1(0x12b3220, 0xc4202c7c70, 0xc42153b590)
        /src/github.com/TykTechnologies/tyk/middleware.go:76 +0x637
net/http.HandlerFunc.ServeHTTP(0xc4222f4cc0, 0x12b3220, 0xc4202c7c70, 0xc42153b590)
        /usr/local/go/src/net/http/server.go:1726 +0x44
main.CreateMiddleware.func1.1(0x12b3220, 0xc4202c7c70, 0xc42153b590)
        /src/github.com/TykTechnologies/tyk/middleware.go:100 +0x83c
net/http.HandlerFunc.ServeHTTP(0xc4222f4d00, 0x12b3220, 0xc4202c7c70, 0xc42153b590)
        /usr/local/go/src/net/http/server.go:1726 +0x44
main.CreateMiddleware.func1.1(0x12b3220, 0xc4202c7c70, 0xc42153b590)
        /src/github.com/TykTechnologies/tyk/middleware.go:100 +0x83c
net/http.HandlerFunc.ServeHTTP(0xc4222f4d40, 0x12b3220, 0xc4202c7c70, 0xc42153b590)
        /usr/local/go/src/net/http/server.go:1726 +0x44
main.CreateMiddleware.func1.1(0x12b3220, 0xc4202c7c70, 0xc42153b590)
        /src/github.com/TykTechnologies/tyk/middleware.go:100 +0x83c
net/http.HandlerFunc.ServeHTTP(0xc4222f4d80, 0x12b3220, 0xc4202c7c70, 0xc42153b590)
        /usr/local/go/src/net/http/server.go:1726 +0x44
main.CreateMiddleware.func1.1(0x12b3220, 0xc4202c7c70, 0xc42153b590)
        /src/github.com/TykTechnologies/tyk/middleware.go:100 +0x83c
net/http.HandlerFunc.ServeHTTP(0xc4222f4dc0, 0x12b3220, 0xc4202c7c70, 0xc42153b590)
        /usr/local/go/src/net/http/server.go:1726 +0x44
main.CreateMiddleware.func1.1(0x12b3220, 0xc4202c7c70, 0xc42153b590)
        /src/github.com/TykTechnologies/tyk/middleware.go:100 +0x83c
net/http.HandlerFunc.ServeHTTP(0xc4222f4e00, 0x12b3220, 0xc4202c7c70, 0xc42153b590)
        /usr/local/go/src/net/http/server.go:1726 +0x44
main.CreateMiddleware.func1.1(0x12b3220, 0xc4202c7c70, 0xc42153b590)
        /src/github.com/TykTechnologies/tyk/middleware.go:100 +0x83c
net/http.HandlerFunc.ServeHTTP(0xc4222f4e40, 0x12b3220, 0xc4202c7c70, 0xc42153b590)
        /usr/local/go/src/net/http/server.go:1726 +0x44
main.CreateMiddleware.func1.1(0x12b3220, 0xc4202c7c70, 0xc42153b590)
        /src/github.com/TykTechnologies/tyk/middleware.go:100 +0x83c
net/http.HandlerFunc.ServeHTTP(0xc4222f4e80, 0x12b3220, 0xc4202c7c70, 0xc42153b590)
        /usr/local/go/src/net/http/server.go:1726 +0x44
main.CreateMiddleware.func1.1(0x12b3220, 0xc4202c7c70, 0xc42153b590)
        /src/github.com/TykTechnologies/tyk/middleware.go:100 +0x83c
net/http.HandlerFunc.ServeHTTP(0xc4222f4ec0, 0x12b3220, 0xc4202c7c70, 0xc42153b590)
        /usr/local/go/src/net/http/server.go:1726 +0x44
github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420218f00, 0x12b3220, 0xc4202c7c70, 0xc42153b590)
        /src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/mux.go:114 +0x10d
net/http.(*ServeMux).ServeHTTP(0xc422302f30, 0x12b3220, 0xc4202c7c70, 0xc42153b3b0)
        /usr/local/go/src/net/http/server.go:2022 +0x7f
net/http.serverHandler.ServeHTTP(0xc420a2a000, 0x12b3220, 0xc4202c7c70, 0xc42153b3b0)
        /usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc421423d80, 0x12b42a0, 0xc4213ce4c0)
        /usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2293 +0x44d
```
**What is the expected behavior?**
No error.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Add meta data key:value pair:
`contact:0`
Add header:value pair:
`X-Contact: $tyk_meta.contact`
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.3.5 / 1.3.5

Problem does not exist with value 1 instead of 0.

### PR DESCRIPTION
**Pull request by mvdan**
That's all we support and what the documentation says. We already
enforce this on master.

This way, if someone tries to create a key with metadata that isn't an
object or contains something other than keys, the key creation will just
error.

Fixes #944.

### CODE REVIEW

File: middleware_url_rewrite.go [hunk 1]
```diff
@@ -113,34 +113,10 @@ func (u URLRewriter) Rewrite(thisMeta *tykcommon.URLRewriteMeta, path string, us
 			contextKey := strings.Replace(v[0], "$tyk_meta.", "", 1)
 			log.Debug("Replacing: ", v[0])
 
-			tempVal, ok := thisSessionState.MetaData.(map[string]interface{})[contextKey]
+			tempVal, ok := thisSessionState.MetaData[contextKey]
 			if ok {
-				var nVal string
```
Comment (buger) [inline middleware_url_rewrite.go]: Looks like a big chunk of code...

In master we still use valToStr https://github.com/TykTechnologies/tyk/blob/master/mw_url_rewrite.go#L90

Comment (mvdan) [inline middleware_url_rewrite.go]: I looked into the same before - it's used in multiple places. This one was removed from master too, as there is no interface type here. The new code is:

```
val, ok := session.MetaData[contextKey]
if ok {
        newpath = strings.Replace(newpath, v[0],
                url.QueryEscape(valToStr(val)), -1)
}
```

Note that `valToStr` does nothing for strings, and the same applies to the deleted chunk of code.
