### PR TITLE
all: various cleanups and simplifications, fix response transforms

### LINKED ISSUE #1041: Activating a response middleware causes a panic
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When I use response middleware (e.g. body transform), the gateway panics

**What is the expected behavior?**
It should not panic

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1. Create an API
2. Add a response transform to a path
3. Start gateway
4. Make request 
5. Panic

Output:

```
2017/08/29 04:14:25 http: panic serving 172.18.0.1:51626: runtime error: invalid memory address or nil pointer dereference
goroutine 11912 [running]:
net/http.(*conn).serve.func1(0xc421898fa0)
        /usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0xc85500, 0x131dd30)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
main.(*APISpec).Version(0x0, 0xc4200dbf00, 0x4, 0xd, 0x1, 0xc423782f60, 0xc4233d2d50, 0xc422ccc7c0, 0x0)
        /develop/go/src/github.com/TykTechnologies/tyk/api_definition.go:1068 +0xe0
main.(*ResponseTransformMiddleware).HandleResponse(0xc4233dedd0, 0x126c6e0, 0xc421564000, 0xc4230ff5f0, 0xc4200dbf00, 0xc42186f8c0, 0x0, 0x0)
        /develop/go/src/github.com/TykTechnologies/tyk/res_handler_transform.go:38 +0x6b
main.handleResponseChain(0xc4233dedc0, 0x1, 0x1, 0x126c6e0, 0xc421564000, 0xc4230ff5f0, 0xc4200dbf00, 0xc42186f8c0, 0xc422565ea0, 0xc423782cc4)
        /develop/go/src/github.com/TykTechnologies/tyk/middleware.go:142 +0x8f
main.(*ReverseProxy).WrappedServeHTTP(0xc422f9c740, 0x126c6e0, 0xc421564000, 0xc4200dbf00, 0x59a4ea00, 0x0)
        /develop/go/src/github.com/TykTechnologies/tyk/reverse_proxy.go:601 +0x18a2
main.(*ReverseProxy).ServeHTTP(0xc422f9c740, 0x126c6e0, 0xc421564000, 0xc4200dbf00, 0x0)
        /develop/go/src/github.com/TykTechnologies/tyk/reverse_proxy.go:362 +0x60
main.(*SuccessHandler).ServeHTTP(0xc42000f0b8, 0x126c6e0, 0xc421564000, 0xc4200dbf00, 0x0)
        /develop/go/src/github.com/TykTechnologies/tyk/handler_success.go:338 +0x174
main.(*DummyProxyHandler).ServeHTTP(0xc42000f0b8, 0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /develop/go/src/github.com/TykTechnologies/tyk/api_loader.go:553 +0x4b
main.CreateMiddleware.func1.1(0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /develop/go/src/github.com/TykTechnologies/tyk/middleware.go:87 +0x7de
net/http.HandlerFunc.ServeHTTP(0xc422f9c800, 0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
main.CreateMiddleware.func1.1(0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /develop/go/src/github.com/TykTechnologies/tyk/middleware.go:87 +0x7de
net/http.HandlerFunc.ServeHTTP(0xc422f9c840, 0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
main.CreateMiddleware.func1.1(0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /develop/go/src/github.com/TykTechnologies/tyk/middleware.go:87 +0x7de
net/http.HandlerFunc.ServeHTTP(0xc422f9c880, 0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
main.CreateMiddleware.func1.1(0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /develop/go/src/github.com/TykTechnologies/tyk/middleware.go:87 +0x7de
net/http.HandlerFunc.ServeHTTP(0xc422f9c8c0, 0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
main.CreateMiddleware.func1.1(0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /develop/go/src/github.com/TykTechnologies/tyk/middleware.go:87 +0x7de
net/http.HandlerFunc.ServeHTTP(0xc422f9c900, 0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
main.CreateMiddleware.func1.1(0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /develop/go/src/github.com/TykTechnologies/tyk/middleware.go:87 +0x7de
net/http.HandlerFunc.ServeHTTP(0xc422f9c940, 0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
main.CreateMiddleware.func1.1(0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /develop/go/src/github.com/TykTechnologies/tyk/middleware.go:87 +0x7de
net/http.HandlerFunc.ServeHTTP(0xc422f9c980, 0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
main.CreateMiddleware.func1.1(0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /develop/go/src/github.com/TykTechnologies/tyk/middleware.go:87 +0x7de
net/http.HandlerFunc.ServeHTTP(0xc422f9c9c0, 0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
main.CreateMiddleware.func1.1(0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /develop/go/src/github.com/TykTechnologies/tyk/middleware.go:87 +0x7de
net/http.HandlerFunc.ServeHTTP(0xc422f9ca00, 0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4202fcb40, 0x126c6e0, 0xc421564000, 0xc4200dbf00)
        /develop/go/src/github.com/TykTechnologies/tyk/vendor/github.com/gorilla/mux/mux.go:114 +0x10c
net/http.(*ServeMux).ServeHTTP(0xc4233c7320, 0x126c6e0, 0xc421564000, 0xc422ff7100)
        /usr/local/go/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc4203a7970, 0x126c6e0, 0xc421564000, 0xc422ff7100)
        /usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc421898fa0, 0x126d4e0, 0xc4232b68c0)
        /usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2668 +0x2ce
```

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Master

### PR DESCRIPTION
**Pull request by mvdan**
This started as a simplification of the API loader, but I kept finding
other stuff to do.

* Inline some small funcs that are only used once
* Remove no-op use of mapstructure
* Log errors on the Init call sites, not in their bodies
* ResponseHandlersActive is useless (ranging over empty slice is a no-op
  already)

Also happened to fix an Init that didn't properly assign the Spec field
of the receiver, which was already reported in the issue tracker due to
a panic.

Fixes #1041.

### CODE REVIEW

File: res_handler_transform.go [hunk 1]
```diff
@@ -9,28 +9,16 @@ import (
...
 
 func (h *ResponseTransformMiddleware) Init(c interface{}, spec *APISpec) error {
-	handler := ResponseTransformMiddleware{}
-
-	if err := mapstructure.Decode(c, &h.config); err != nil {
-		log.Error(err)
-		return err
-	}
-	handler.Spec = spec
+	h.Spec = spec
```
Comment (mvdan) [inline res_handler_transform.go]: @buger actually, I think this is the fix for https://github.com/TykTechnologies/tyk/issues/1041 (by pure chance - I found this broken code, and remembered that issue after fixing it)

Comment (mvdan) [reply res_handler_transform.go]: sure seems like it - updated issue.
